### ISSUE TITLE
no route match 'omniauth/sign_in'

### ISSUE THREAD

**Issue by islam-taha** [zquestz/omniauth-google-oauth2#227]
as the title suggests my problem is about routing error here is the log from the error
```
I, [2016-02-07T21:41:54.923380 #41972]  INFO -- : Started GET "/omniauth/sign_in?resource_class=User" for ::1 at 2016-02-07 21:41:54 +0200
F, [2016-02-07T21:41:54.929088 #41972] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/omniauth/sign_in"):
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:22:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'


F, [2016-02-07T21:41:54.929493 #41972] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/omniauth/sign_in"):
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:22:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

and here is my routes.rb
```
require 'resque'
require 'resque/scheduler'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "callbacks"
  }

  # API documentation route
  apipie
  # API routes
  namespace :api, defaults: { format: :json }, except: [:new, :edit] do
    scope module: :v1, constraints: ApiConstraint.new(version: 1) do
      mount_devise_token_auth_for 'User', at: 'auth', format: 'json'
      
      resources :users do
        collection do
          get 'can'
        end
      end
      
    end
    
    match "*path", to: -> (env) { [404, { Error: 'Endpoint not implemented'}, []] }, via: :all
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Resque::Server.new, :at => '/resque'

  # Static pages route
  get 'pages/*page' => 'home#show', constraints: { page: /[a-zA-Z].*/ }, as: 'page'
  root to: 'home#index'
end
```

**Comment by michal-kazmierczak** [comment]
Indeed your `routes.rb` doesn't generate such path. 
Run `rake routes` to see available paths.

If you have set up initializer you should be able to use following link `<%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %>` which generates `/users/auth/google_oauth2` path.

**Comment by islam-taha** [comment]
i think i badly explained my problem.
the problem is that google auth redirect me to the unkown route above not to the right devise sign in route

**Comment by michal-kazmierczak** [comment]
how is your application configured on the Google Console side? I guess you should fix redirect URL.

**Comment by islam-taha** [comment]
redirect url wasn't the same one in the console, when i changed the prefix of omniauth to /auth/ it worked will and didnt't redirect me to this unkown route

**Comment by zquestz** [comment]
If you go this working, can you share exactly what you did. I know this was working in devise, curious what changed.

**Comment by islam-taha** [comment]
As i mentioned in my last comment i changed omniauth_prefix in devise.rb to 'api/auth' in my case from 'omniauth' then google_oauth2 redirected me to api/auth/sign_in instead of omniauth/sign_in.
It seems that omniauth set the redirect url from the omniauth_prefix when i put anything in the prefix like 'api/me' it redirect me to api/me/sign_in.
Is this the proper fix for this problem ?

**Comment by zquestz** [comment]
That should be fine if you got it up and running. Thanks for reporting the issue.
