### ISSUE TITLE
Does not work with Hashie 3.4.5

### ISSUE THREAD

**Issue by KMarshland** [zquestz/omniauth-google-oauth2#249]
As per the title, this gem threw an error when I switched from Hashie 3.4.4 to Hashie 3.4.5. The error occurred when I tried running `bundle exec rake assets:precompile`, but I suspect it would also have thrown an error when I tried to start the server -- precompiling assets was merely run first. 

Stacktrace: 
```
Bundler::GemRequireError: There was an error while trying to load the gem 'omniauth-google-oauth2'.
Gem Load Error is: uninitialized constant Hashie::Extensions::Array
Did you mean?  Hashie::Array
               Array
Backtrace for gem load error is:
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.4.5/lib/hashie/array.rb:3:in `<class:Array>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.4.5/lib/hashie/array.rb:2:in `<module:Hashie>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.4.5/lib/hashie/array.rb:1:in `<top (required)>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.4.5/lib/hashie/mash.rb:2:in `require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/hashie-3.4.5/lib/hashie/mash.rb:2:in `<top (required)>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:1:in `require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:1:in `<top (required)>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:15:in `require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:15:in `<class:OAuth2>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:14:in `<module:Strategies>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:8:in `<module:OmniAuth>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:7:in `<top (required)>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-google-oauth2-0.4.1/lib/omniauth/strategies/google_oauth2.rb:3:in `require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-google-oauth2-0.4.1/lib/omniauth/strategies/google_oauth2.rb:3:in `<top (required)>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-google-oauth2-0.4.1/lib/omniauth/google_oauth2.rb:1:in `require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-google-oauth2-0.4.1/lib/omniauth/google_oauth2.rb:1:in `<top (required)>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-google-oauth2-0.4.1/lib/omniauth-google-oauth2.rb:1:in `require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/omniauth-google-oauth2-0.4.1/lib/omniauth-google-oauth2.rb:1:in `<top (required)>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:86:in `require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:81:in `each'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:81:in `block in require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:70:in `each'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:70:in `require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler.rb:102:in `require'
```

I was able to fix this by manually uninstalling hashie 3.4.5 and adding `gem 'hashie', '3.4.4'` to my gemfile explicitly.

**Comment by zquestz** [comment]
Appears the bug was in hashie. 3.4.6 is already out and resolves the issue.
