### ISSUE TITLE
OmniAuth::NoSessionError (You must provide a session to use OmniAuth.) on Rails 5 --api

### ISSUE THREAD

**Issue by FPierre** [zquestz/omniauth-google-oauth2#287]
Hello, thanks for this gem.

I currently have the following problem:

```
$ rails server

=> Booting WEBrick

...blah blah

Started GET "/" for 127.0.0.1 at 2017-06-24 18:09:45 +0200

...blah blah

OmniAuth::NoSessionError (You must provide a session to use OmniAuth.)
omniauth (1.6.1) lib/omniauth/strategy.rb:178:in `call!'
omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
activerecord (5.1.1) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.1) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.1) lib/rails/engine.rb:522:in `call'
rack (2.0.3) lib/rack/handler/webrick.rb:86:in `service'
/home/pierre/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
/home/pierre/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
/home/pierre/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
```

Devise :

```
# config/initializers/devise.rb

# ...

  config.omniauth(
    :google_oauth2,
    Rails.application.secrets.google_client_id,
    Rails.application.secrets.google_client_secret,
    {}
  )

# ...

```

Routes :

```
# config/routes.rb

Rails.application.routes.draw do
  devise_for :internal_users, controllers: { omniauth_callbacks: 'internal_users/omniauth_callbacks' }
end
```

Model :

```
# app/models/internal_user.rb

class InternalUser < ApplicationRecord
  devise :database_authenticatable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :omniauthable,
         omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    InternalUser.find_by! email: data['email']
  end
end
```

Stack :

Rails 5.1.1 API mode
Gem Devise 4.3 (configured following your documentation)
Gem omniauth-google-oauth2 0.5.0

Any idea?

**Comment by zquestz** [comment]
This thread should help you. =)

https://stackoverflow.com/questions/38424133/getting-error-omniauthnosessionerror-with-rails-5-api

**Comment by JattCoder** [comment]
#config/application.rb
change api_only to [false]
