### ISSUE TITLE
Faraday::ConnectionFailed (execution expired) on callback

### ISSUE THREAD

**Issue by OrrYakobiStudent** [zquestz/omniauth-google-oauth2#295]
I cannot figure why I keep getting the following error:

```
omniauth: (google_oauth2) Callback phase initiated.
Faraday::ConnectionFailed (execution expired):

/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `initialize'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `open'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `block in connect'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:876:in `start'
/Users/orryakobi/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1407:in `request'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:80:in `perform_request'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:38:in `block in call'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:33:in `call'
faraday (0.12.2) lib/faraday/request/url_encoded.rb:15:in `call'
faraday (0.12.2) lib/faraday/rack_builder.rb:141:in `build_response'
faraday (0.12.2) lib/faraday/connection.rb:386:in `run_request'
oauth2 (1.4.0) lib/oauth2/client.rb:99:in `request'
oauth2 (1.4.0) lib/oauth2/client.rb:146:in `get_token'
oauth2 (1.4.0) lib/oauth2/strategy/auth_code.rb:30:in `get_token'
omniauth-google-oauth2 (0.5.1) lib/omniauth/strategies/google_oauth2.rb:120:in `get_access_token'
omniauth-google-oauth2 (0.5.1) lib/omniauth/strategies/google_oauth2.rb:94:in `custom_build_access_token'
omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:73:in `callback_phase'
omniauth (1.6.1) lib/omniauth/strategy.rb:230:in `callback_call'
omniauth (1.6.1) lib/omniauth/strategy.rb:187:in `call!'
omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
omniauth (1.6.1) lib/omniauth/builder.rb:63:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.2) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.2) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Here's the code I have implemented in my project. Also, I'm using Rails 5.1.2  

config/initializers/omniauth.rb:
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV['GOOGLE_OAUTH_ID'], ENV['GOOGLE_OAUTH_SECRET'], 
  {
  	scope: 'email,profile'
  }
end
```
config/routes.rb:
```
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  match 'auth/google_oauth2/callback', to: 'welcome#auth' , via:[:get]
end
```

**Comment by zquestz** [comment]
This should work just fine. This is failing when running get_token in the omniauth-oauth2 code, you might want to ping them.

A few things you might check:
* Is anything preventing the app from making a request (little snitch, firewall, etc)
* Try the example app and see if it is doing the same thing. This has been tested on Ruby 2.4 and known to work.

**Comment by OrrYakobiStudent** [comment]
I went ahead and pinged omniauth-oauth2 about the issue. Also checked and there is anything thats blocking the app from making a request.

How do I set up the example app? I could not get it to run

**Comment by zquestz** [comment]
Just clone this repo. Go to the `examples` directory and set the following ENV vars:

```
export GOOGLE_KEY=KEY
export GOOGLE_SECRET=SEC
```

Then run the app with:

```
bundle install
bundle exec rackup -p <PORT>
```

**Comment by Evan-M** [comment]
@OrrYakobiStudent I'm having the same issue, with essentially the same stack trace.  I was able to get the example app in this repo running, but I encounter the same error there (with the same stack trace).  

I also noticed that the stack trace included in the closed issue https://github.com/zquestz/omniauth-google-oauth2/issues/284 is the same; I think this is a duplicate issue.  In the case of https://github.com/zquestz/omniauth-google-oauth2/issues/284, it was reported that the error resolved itself with no code or config changes the day after it was initially reported.  @Benratelade suspected that there is a delay from Google when enabling APIs.

Not sure if any of this info helps. I'm still looking for a solution, but may just try again tomorrow.

**Comment by basisworldwide** [comment]
@Evan-M Thanks so much for the info, any updates?

**Comment by OrrYakobiStudent** [comment]
@Evan-M Thanks so much for the info, any updates?

**Comment by zquestz** [comment]
Sorry for the delayed response. Did you get this resolved?

**Comment by zquestz** [comment]
Will reopen if OP comments.

**Comment by andi-dev** [comment]
I am just facing the same issue, however it works for my coworker with the same code and same keys.
