### ISSUE TITLE
invalid_client:  { "error" : "invalid_client" }

### ISSUE THREAD

**Issue by CoderPuppy** [zquestz/omniauth-google-oauth2#36]
When I try to use this it gets to the callback url (/auth/google_oauth2/callback) but shows this

```
OAuth2::Error

invalid_client: 
{
  "error" : "invalid_client"
}
```

Stack trace:

```
oauth2 (0.8.0) lib/oauth2/client.rb:108:in `request'
oauth2 (0.8.0) lib/oauth2/client.rb:131:in `get_token'
oauth2 (0.8.0) lib/oauth2/strategy/auth_code.rb:29:in `get_token'
omniauth-oauth2 (1.1.0) lib/omniauth/strategies/oauth2.rb:100:in `build_access_token'
omniauth-oauth2 (1.1.0) lib/omniauth/strategies/oauth2.rb:75:in `callback_phase'
omniauth (1.1.0) lib/omniauth/strategy.rb:219:in `callback_call'
omniauth (1.1.0) lib/omniauth/strategy.rb:175:in `call!'
omniauth (1.1.0) lib/omniauth/strategy.rb:157:in `call'
omniauth (1.1.0) lib/omniauth/strategy.rb:177:in `call!'
omniauth (1.1.0) lib/omniauth/strategy.rb:157:in `call'
omniauth (1.1.0) lib/omniauth/builder.rb:48:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.1) lib/rack/etag.rb:23:in `call'
rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/cookies.rb:338:in `call'
activerecord (3.2.6) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `_run__221833846075497048__call__1546209218515107876__callbacks'
activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.6) lib/rails/rack/logger.rb:26:in `call_app'
railties (3.2.6) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.1) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.6) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.1) lib/rack/lock.rb:15:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/static.rb:62:in `call'
railties (3.2.6) lib/rails/engine.rb:479:in `call'
railties (3.2.6) lib/rails/application.rb:220:in `call'
railties (3.2.6) lib/rails/railtie/configurable.rb:30:in `method_missing'
passenger (3.0.13) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
passenger (3.0.13) lib/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
passenger (3.0.13) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
passenger (3.0.13) lib/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
passenger (3.0.13) lib/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
passenger (3.0.13) lib/phusion_passenger/utils.rb:479:in `safe_fork'
passenger (3.0.13) lib/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
passenger (3.0.13) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.13) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.13) lib/phusion_passenger/abstract_server.rb:180:in `start'
passenger (3.0.13) lib/phusion_passenger/rack/application_spawner.rb:129:in `start'
passenger (3.0.13) lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
passenger (3.0.13) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
passenger (3.0.13) lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
passenger (3.0.13) lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
<internal:prelude>:10:in `synchronize'
passenger (3.0.13) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
passenger (3.0.13) lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
passenger (3.0.13) lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
passenger (3.0.13) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
passenger (3.0.13) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.13) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.13) helper-scripts/passenger-spawn-server:99:in `<main>'
```

**Comment by indrapermanarusli** [comment]
Where can I get the client secret for type: installed application? Is it the same with the API Key?
