### ISSUE TITLE
Legacy People API no longer available for new projects

### ISSUE THREAD

**Issue by Waseem-Q** [zquestz/omniauth-google-oauth2#379]
This gem uses the legacy people api to perform oauth with Google. That API is only available for projects already using it, and not available for new projects. If a project disables the API, it can not be re-enabled.

https://developers.google.com/people/legacy#why_is_the_legacy_people_api_enabled_for_my_developer_project

**Comment by Waseem-Q** [comment]
`OAuth2::Error {"code"=>403, "message"=>"Legacy People API has not been used in project 1070582368186 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=############# then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",`

```
oauth2 (1.4.0) lib/oauth2/client.rb:119:in `request'
oauth2 (1.4.0) lib/oauth2/access_token.rb:107:in `request'
oauth2 (1.4.0) lib/oauth2/access_token.rb:114:in `get'
omniauth-google-oauth2 (0.5.2) lib/omniauth/strategies/google_oauth2.rb:83:in `raw_info'
omniauth-google-oauth2 (0.5.2) lib/omniauth/strategies/google_oauth2.rb:44:in `block in <class:GoogleOauth2>'
omniauth (1.7.1) lib/omniauth/strategy.rb:109:in `instance_eval'
omniauth (1.7.1) lib/omniauth/strategy.rb:109:in `block in compile_stack'
omniauth (1.7.1) lib/omniauth/strategy.rb:108:in `each'
omniauth (1.7.1) lib/omniauth/strategy.rb:108:in `inject'
omniauth (1.7.1) lib/omniauth/strategy.rb:108:in `compile_stack'
omniauth (1.7.1) lib/omniauth/strategy.rb:102:in `uid_stack'
omniauth (1.7.1) lib/omniauth/strategy.rb:329:in `uid'
omniauth (1.7.1) lib/omniauth/strategy.rb:345:in `auth_hash'
omniauth (1.7.1) lib/omniauth/strategy.rb:368:in `callback_phase'
omniauth-oauth2 (1.3.1) lib/omniauth/strategies/oauth2.rb:79:in `callback_phase'
omniauth (1.7.1) lib/omniauth/strategy.rb:236:in `callback_call'
omniauth (1.7.1) lib/omniauth/strategy.rb:188:in `call!'
omniauth (1.7.1) lib/omniauth/strategy.rb:168:in `call'
omniauth (1.7.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.7.1) lib/omniauth/strategy.rb:168:in `call'
omniauth (1.7.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.7.1) lib/omniauth/strategy.rb:168:in `call'
omniauth (1.7.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.7.1) lib/omniauth/strategy.rb:168:in `call'
omniauth (1.7.1) lib/omniauth/builder.rb:63:in `call'
```

**Comment by Waseem-Q** [comment]
If anyone has any suggestions for a new omniauth strategy that works with Google OAuth, please let me know.  Fwiw, the Omniauth strategy wiki page links to this gem as the most recent/active.

**Comment by zquestz** [comment]
Sad news indeed. Seems they are forcing people onto their new people api's. Hopefully have some time this weekend to try and get the flow updated.

**Comment by bkoski** [comment]
For me, updating to the latest gem version (0.8.0) resolved the issue.  It seems that the changes introduced in e3cbdc512a020249e201300df01ed4ddde78d176 avoid this deprecation error.

**Comment by zquestz** [comment]
@Waseem-Q which version are you using?

**Comment by zquestz** [comment]
Latest version works, no activity. Closing.
