### ISSUE TITLE
Can't test the callback controller

### ISSUE THREAD

**Issue by phuongnd08** [zquestz/omniauth-google-oauth2#468]
I would like to test the callback controller:

# spec/support/omniauth.rb
```
module OmniauthMacros
  def mock_auth_hash(provider: :google_oauth2, email: 'testuser@example.com', name: 'Test User', uid: '123456789')
    case provider
    when :facebook
      OmniAuth::AuthHash.new({
        provider: 'facebook',
        uid: '123545',
        info: {
          email: 'testuser@example.com',
          name: 'Test User'
        },
        credentials: {
          token: 'mock_token',
          expires_at: Time.now + 1.week
        }
      })
    when :google_oauth2
      OmniAuth::AuthHash.new({
        provider: 'google_oauth2',
        uid: '1234567890',
        info: {
          email: 'testuser_google@example.com',
          name: 'Test User Google'
        },
        credentials: {
          token: 'mock_token_google',
          expires_at: Time.now + 1.week
        }
      })
    end
  end

  def mock_auth_failure(provider: :google_oauth2, message: :invalid_credentials)
    OmniAuth.config.mock_auth[provider] = :invalid_credentials
  end
end

RSpec.configure do |config|
  config.include OmniauthMacros

  original_failure_handler = OmniAuth.config.on_failure

  config.before(:each) do
    OmniAuth.config.test_mode = true
    original_failure_handler = OmniAuth.config.on_failure

    local_failure_handler = proc do |env|
      error = OmniAuth::Strategies::OAuth2::CallbackError.new(
        "Callback error", "Error reason", "https://example.com/error"
      )
      env["omniauth.error"] = error
      env
    end
    # here we compose the two handlers into a single function,
    # the result will be global_failure_handler(local_failure_handler(env))
    failure_handler = original_failure_handler << local_failure_handler

    OmniAuth.config.on_failure = failure_handler
  end

  config.after(:each) do
    OmniAuth.config.test_mode = false
    OmniAuth.config.on_failure = original_failure_handler
  end
end
```

# app/models/user.rb
```
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise(
    :trackable,
    :omniauthable,
    omniauth_providers: [:google_oauth2, :facebook],
  )

  has_many :club_admins
  has_many :clubs, through: :club_admins
  has_many :owned_club_admins, -> { owner }, class_name: "ClubAdmin", foreign_key: "admin_id"
  has_many :owned_clubs, through: :owned_club_admins, source: :club

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data["email"]).first

    # Uncomment the section below if you want users to be created if they don't exist
    user ||= User.create(
      name: data["name"],
      email: data["email"]
    )
    user
  end
end
```
# config/initializers/devise.rb
```
# frozen_string_literal: true

# Assuming you have not yet modified this file, each configuration option below
# is set to its default value. Note that some are commented out while others
# are not: uncommented lines are intended to protect your configuration from
# breaking changes in upgrades (i.e., in the event that future versions of
# Devise change the default values for those options).
#
# Use this hook to configure devise mailer, warden hooks and so forth.
# Many of these configuration options can be set straight in your model.
Devise.setup do |config|
  # The secret key used by Devise. Devise uses this key to generate
  # random tokens. Changing this key will render invalid all existing
  # confirmation, reset password and unlock tokens in the database.
  # Devise will use the `secret_key_base` as its `secret_key`
  # by default. You can change it below and use your own secret key.
  # config.secret_key = 'ac1d69eda7609631a5bc1dfc3c2a977883cc1ac61c380ffed94117dd7c6116de0d54c020f8e5ef60e41c723387298e4af693398d8bc9661de02aa9705d6cb497'

  # ==> Controller configuration
  # Configure the parent class to the devise controllers.
  # config.parent_controller = 'DeviseController'

  # ==> Mailer Configuration
  # Configure the e-mail address which will be shown in Devise::Mailer,
  # note that it will be overwritten if you use your own mailer class
  # with default "from" parameter.
  config.mailer_sender = "please-change-me-at-config-initializers-devise@example.com"

  # Configure the class responsible to send e-mails.
  # config.mailer = 'Devise::Mailer'

  # Configure the parent class responsible to send e-mails.
  # config.parent_mailer = 'ActionMailer::Base'

  # ==> ORM configuration
  # Load and configure the ORM. Supports :active_record (default) and
  # :mongoid (bson_ext recommended) by default. Other ORMs may be
  # available as additional gems.
  require "devise/orm/active_record"

  # ==> Configuration for any authentication mechanism
  # Configure which keys are used when authenticating a user. The default is
  # just :email. You can configure it to use [:username, :subdomain], so for
  # authenticating a user, both parameters are required. Remember that those
  # parameters are used only when authenticating and not when retrieving from
  # session. If you need permissions, you should implement that in a before filter.
  # You can also supply a hash where the value is a boolean determining whether
  # or not authentication should be aborted when the value is not present.
  # config.authentication_keys = [:email]

  # Configure parameters from the request object used for authentication. Each entry
  # given should be a request method and it will automatically be passed to the
  # find_for_authentication method and considered in your model lookup. For instance,
  # if you set :request_keys to [:subdomain], :subdomain will be used on authentication.
  # The same considerations mentioned for authentication_keys also apply to request_keys.
  # config.request_keys = []

  # Configure which authentication keys should be case-insensitive.
  # These keys will be downcased upon creating or modifying a user and when used
  # to authenticate or find a user. Default is :email.
  config.case_insensitive_keys = [:email]

  # Configure which authentication keys should have whitespace stripped.
  # These keys will have whitespace before and after removed upon creating or
  # modifying a user and when used to authenticate or find a user. Default is :email.
  config.strip_whitespace_keys = [:email]

  # Tell if authentication through request.params is enabled. True by default.
  # It can be set to an array that will enable params authentication only for the
  # given strategies, for example, `config.params_authenticatable = [:database]` will
  # enable it only for database (email + password) authentication.
  # config.params_authenticatable = true

  # Tell if authentication through HTTP Auth is enabled. False by default.
  # It can be set to an array that will enable http authentication only for the
  # given strategies, for example, `config.http_authenticatable = [:database]` will
  # enable it only for database authentication.
  # For API-only applications to support authentication "out-of-the-box", you will likely want to
  # enable this with :database unless you are using a custom strategy.
  # The supported strategies are:
  # :database      = Support basic authentication with authentication key + password
  # config.http_authenticatable = false

  # If 401 status code should be returned for AJAX requests. True by default.
  # config.http_authenticatable_on_xhr = true

  # The realm used in Http Basic Authentication. 'Application' by default.
  # config.http_authentication_realm = 'Application'

  # It will change confirmation, password recovery and other workflows
  # to behave the same regardless if the e-mail provided was right or wrong.
  # Does not affect registerable.
  # config.paranoid = true

  # By default Devise will store the user in session. You can skip storage for
  # particular strategies by setting this option.
  # Notice that if you are skipping storage for all authentication paths, you
  # may want to disable generating routes to Devise's sessions controller by
  # passing skip: :sessions to `devise_for` in your config/routes.rb
  config.skip_session_storage = [:http_auth]

  # By default, Devise cleans up the CSRF token on authentication to
  # avoid CSRF token fixation attacks. This means that, when using AJAX
  # requests for sign in and sign up, you need to get a new CSRF token
  # from the server. You can disable this option at your own risk.
  # config.clean_up_csrf_token_on_authentication = true

  # When false, Devise will not attempt to reload routes on eager load.
  # This can reduce the time taken to boot the app but if your application
  # requires the Devise mappings to be loaded during boot time the application
  # won't boot properly.
  # config.reload_routes = true

  # ==> Configuration for :database_authenticatable
  # For bcrypt, this is the cost for hashing the password and defaults to 12. If
  # using other algorithms, it sets how many times you want the password to be hashed.
  # The number of stretches used for generating the hashed password are stored
  # with the hashed password. This allows you to change the stretches without
  # invalidating existing passwords.
  #
  # Limiting the stretches to just one in testing will increase the performance of
  # your test suite dramatically. However, it is STRONGLY RECOMMENDED to not use
  # a value less than 10 in other environments. Note that, for bcrypt (the default
  # algorithm), the cost increases exponentially with the number of stretches (e.g.
  # a value of 20 is already extremely slow: approx. 60 seconds for 1 calculation).
  config.stretches = Rails.env.test? ? 1 : 12

  # Set up a pepper to generate the hashed password.
  # config.pepper = '447bbc7c55f87838d82335b81618db9f468237a061684fa3291a9f23f9bfc14f2427844046b41937efb565129e3a404107f339580cee5e78661d8a80a6924706'

  # Send a notification to the original email when the user's email is changed.
  # config.send_email_changed_notification = false

  # Send a notification email when the user's password is changed.
  # config.send_password_change_notification = false

  # ==> Configuration for :confirmable
  # A period that the user is allowed to access the website even without
  # confirming their account. For instance, if set to 2.days, the user will be
  # able to access the website for two days without confirming their account,
  # access will be blocked just in the third day.
  # You can also set it to nil, which will allow the user to access the website
  # without confirming their account.
  # Default is 0.days, meaning the user cannot access the website without
  # confirming their account.
  # config.allow_unconfirmed_access_for = 2.days

  # A period that the user is allowed to confirm their account before their
  # token becomes invalid. For example, if set to 3.days, the user can confirm
  # their account within 3 days after the mail was sent, but on the fourth day
  # their account can't be confirmed with the token any more.
  # Default is nil, meaning there is no restriction on how long a user can take
  # before confirming their account.
  # config.confirm_within = 3.days

  # If true, requires any email changes to be confirmed (exactly the same way as
  # initial account confirmation) to be applied. Requires additional unconfirmed_email
  # db field (see migrations). Until confirmed, new email is stored in
  # unconfirmed_email column, and copied to email column on successful confirmation.
  config.reconfirmable = true

  # Defines which key will be used when confirming an account
  # config.confirmation_keys = [:email]

  # ==> Configuration for :rememberable
  # The time the user will be remembered without asking for credentials again.
  # config.remember_for = 2.weeks

  # Invalidates all the remember me tokens when the user signs out.
  config.expire_all_remember_me_on_sign_out = true

  # If true, extends the user's remember period when remembered via cookie.
  # config.extend_remember_period = false

  # Options to be passed to the created cookie. For instance, you can set
  # secure: true in order to force SSL only cookies.
  # config.rememberable_options = {}

  # ==> Configuration for :validatable
  # Range for password length.
  config.password_length = 6..128

  # Email regex used to validate email formats. It simply asserts that
  # one (and only one) @ exists in the given string. This is mainly
  # to give user feedback and not to assert the e-mail validity.
  config.email_regexp = /\A[^@\s]+@[^@\s]+\z/

  # ==> Configuration for :timeoutable
  # The time you want to timeout the user session without activity. After this
  # time the user will be asked for credentials again. Default is 30 minutes.
  # config.timeout_in = 30.minutes

  # ==> Configuration for :lockable
  # Defines which strategy will be used to lock an account.
  # :failed_attempts = Locks an account after a number of failed attempts to sign in.
  # :none            = No lock strategy. You should handle locking by yourself.
  # config.lock_strategy = :failed_attempts

  # Defines which key will be used when locking and unlocking an account
  # config.unlock_keys = [:email]

  # Defines which strategy will be used to unlock an account.
  # :email = Sends an unlock link to the user email
  # :time  = Re-enables login after a certain amount of time (see :unlock_in below)
  # :both  = Enables both strategies
  # :none  = No unlock strategy. You should handle unlocking by yourself.
  # config.unlock_strategy = :both

  # Number of authentication tries before locking an account if lock_strategy
  # is failed attempts.
  # config.maximum_attempts = 20

  # Time interval to unlock the account if :time is enabled as unlock_strategy.
  # config.unlock_in = 1.hour

  # Warn on the last attempt before the account is locked.
  # config.last_attempt_warning = true

  # ==> Configuration for :recoverable
  #
  # Defines which key will be used when recovering the password for an account
  # config.reset_password_keys = [:email]

  # Time interval you can reset your password with a reset password key.
  # Don't put a too small interval or your users won't have the time to
  # change their passwords.
  config.reset_password_within = 6.hours

  # When set to false, does not sign a user in automatically after their password is
  # reset. Defaults to true, so a user is signed in automatically after a reset.
  # config.sign_in_after_reset_password = true

  # ==> Configuration for :encryptable
  # Allow you to use another hashing or encryption algorithm besides bcrypt (default).
  # You can use :sha1, :sha512 or algorithms from others authentication tools as
  # :clearance_sha1, :authlogic_sha512 (then you should set stretches above to 20
  # for default behavior) and :restful_authentication_sha1 (then you should set
  # stretches to 10, and copy REST_AUTH_SITE_KEY to pepper).
  #
  # Require the `devise-encryptable` gem when using anything other than bcrypt
  # config.encryptor = :sha512

  # ==> Scopes configuration
  # Turn scoped views on. Before rendering "sessions/new", it will first check for
  # "users/sessions/new". It's turned off by default because it's slower if you
  # are using only default views.
  # config.scoped_views = false

  # Configure the default scope given to Warden. By default it's the first
  # devise role declared in your routes (usually :user).
  # config.default_scope = :user

  # Set this configuration to false if you want /users/sign_out to sign out
  # only the current scope. By default, Devise signs out all scopes.
  # config.sign_out_all_scopes = true

  # ==> Navigation configuration
  # Lists the formats that should be treated as navigational. Formats like
  # :html should redirect to the sign in page when the user does not have
  # access, but formats like :xml or :json, should return 401.
  #
  # If you have any extra navigational formats, like :iphone or :mobile, you
  # should add them to the navigational formats lists.
  #
  # The "*/*" below is required to match Internet Explorer requests.
  # config.navigational_formats = ['*/*', :html, :turbo_stream]

  # The default HTTP method used to sign out a resource. Default is :delete.
  config.sign_out_via = :get

  # ==> OmniAuth
  # Add a new OmniAuth provider. Check the wiki for more information on setting
  # up on your models and hooks.
  # config.omniauth :github, 'APP_ID', 'APP_SECRET', scope: 'user,public_repo'

  # ==> Warden configuration
  # If you want to use other strategies, that are not supported by Devise, or
  # change the failure app, you can configure them inside the config.warden block.
  #
  config.warden do |manager|
    manager.failure_app = CustomAuthenticationFailureApp
  end

  # ==> Mountable engine configurations
  # When using Devise inside an engine, let's call it `MyEngine`, and this engine
  # is mountable, there are some extra configurations to be taken into account.
  # The following options are available, assuming the engine is mounted as:
  #
  #     mount MyEngine, at: '/my_engine'
  #
  # The router that invoked `devise_for`, in the example above, would be:
  # config.router_name = :my_engine
  #
  # When using OmniAuth, Devise cannot automatically set OmniAuth path,
  # so you need to do it manually. For the users scope, it would be:
  # config.omniauth_path_prefix = '/my_engine/users/auth'

  # ==> Hotwire/Turbo configuration
  # When using Devise with Hotwire/Turbo, the http status for error responses
  # and some redirects must match the following. The default in Devise for existing
  # apps is `200 OK` and `302 Found` respectively, but new apps are generated with
  # these new defaults that match Hotwire/Turbo behavior.
  # Note: These might become the new default in future versions of Devise.
  config.responder.error_status = :unprocessable_entity
  config.responder.redirect_status = :see_other

  # ==> Configuration for :registerable

  # When set to false, does not sign a user in automatically after their password is
  # changed. Defaults to true, so a user is signed in automatically after changing a password.
  # config.sign_in_after_change_password = true

  config.omniauth(
    :google_oauth2,
    Rails.application.credentials.GOOGLE_OAUTH_CLIENT_ID,
    Rails.application.credentials.GOOGLE_OAUTH_SECRET,
    {
      scope: "userinfo.email, userinfo.profile",
      image_aspect_ratio: "square",
      image_size: 50
    }
  )

  config.omniauth(
    :facebook,
    Rails.application.credentials.FACEBOOK_APP_ID,
    Rails.application.credentials.FACEBOOK_APP_SECRET,
    scope: 'email,public_profile',
    info_fields: 'email,name'
  )
end
```
# Gemfile.lock
```
    oauth2 (2.0.9)
      faraday (>= 0.17.3, < 3.0)
      jwt (>= 1.0, < 3.0)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 4)
      snaky_hash (~> 2.0)
      version_gem (~> 1.1)
    omniauth (2.1.2)
      hashie (>= 3.4.6)
      rack (>= 2.2.3)
      rack-protection
    omniauth-facebook (10.0.0)
      bigdecimal
      omniauth-oauth2 (>= 1.2, < 3)
    omniauth-google-oauth2 (1.2.0)
      jwt (>= 2.9)
      oauth2 (~> 2.0)
      omniauth (~> 2.0)
      omniauth-oauth2 (~> 1.8)
    omniauth-oauth2 (1.8.0)
      oauth2 (>= 1.4, < 3)
      omniauth (~> 2.0)
    omniauth-rails_csrf_protection (1.0.2)
      actionpack (>= 4.2)
      omniauth (~> 2.0)
```

# app/controllers/users/omniauth_callbacks_controller.rb
```
# app/controllers/users/omniauth_callbacks_controller.rb

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # Callback cho Facebook
  def facebook
    handle_auth "Facebook"
  end

  # Callback cho Google OAuth2 (nếu cần)
  def google_oauth2
    handle_auth "Google"
  end

  def handle_auth(kind)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # Đăng nhập và chuyển hướng
      set_flash_message(:notice, :success, kind: kind) if is_navigational_format?
    else
      session["devise.#{@user.provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to root_path, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to root_path, alert: request.env["omniauth.error"].message
  end
end
```

# spec/controllers/users/omniauth_callbacks_controller_spec.rb
```
# spec/controllers/users/omniauth_callbacks_controller_spec.rb

require 'rails_helper'

RSpec.describe Users::OmniauthCallbacksController, type: :controller do
  describe "GET #facebook" do
    context "when authentication is successful" do
      it "creates a new user if one does not exist" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        mock_auth_hash(provider: :facebook, email: "testuser@example.com")
        post :facebook
        user = User.find_by(email: "testuser@example.com")
        expect(user).not_to be_nil
        expect(user.provider).to eq("facebook")
        expect(user.uid).to eq("123545")
      end

      it "sets the user_id in session" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        mock_auth_hash(provider: :facebook, email: "testuser@example.com")
        post :facebook
        user = User.find_by(email: "testuser@example.com")
        expect(session[:user_id]).to eq(user.id)
      end

      it "sets a success flash message" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        mock_auth_hash(provider: :facebook, email: "testuser@example.com")
        post :facebook
        expect(flash[:notice]).to eq("Đăng nhập với Facebook thành công.")
      end
    end

    context "when authentication fails" do
      it "redirects to the root path with error message" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        mock_auth_failure(provider: :facebook)
        post :facebook
        expect(response).to redirect_to(root_path)
        expect(flash[:alert]).to eq("Đăng nhập thất bại.")
      end
    end
  end

  describe "GET #google_oauth2" do
    context "when authentication is successful" do
      it "creates a new user if one does not exist" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        mock_auth_hash(provider: :facebook, email: "testuser_google@example.com")
        post :google_oauth2
        user = User.find_by(email: "testuser_google@example.com")
        expect(user).not_to be_nil
        expect(user.provider).to eq("google_oauth2")
        expect(user.uid).to eq("1234567890")
      end

      it "sets the user_id in session" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        mock_auth_hash(provider: :facebook, email: "testuser_google@example.com")
        post :google_oauth2
        user = User.find_by(email: "testuser_google@example.com")
        expect(session[:user_id]).to eq(user.id)
      end

      it "sets a success flash message" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        mock_auth_hash(provider: :facebook, email: "testuser_google@example.com")
        post :google_oauth2
        expect(flash[:notice]).to eq("Đăng nhập với Google thành công.")
      end
    end

    context "when authentication fails" do
      it "redirects to the root path with error message" do
        @request.env["devise.mapping"] = Devise.mappings[:user]
        mock_auth_failure(provider: :google_oauth2)
        post :google_oauth2
        expect(response).to redirect_to(root_path)
        expect(flash[:alert]).to eq("Đăng nhập thất bại.")
      end
    end
  end
end

```

Running the test result in this:

```
1) Users::OmniauthCallbacksController GET #facebook when authentication is successful creates a new user if one does not exist
     Failure/Error: data = access_token.info

     NoMethodError:
       undefined method `info' for nil:NilClass
     # ./app/models/user.rb:16:in `from_omniauth'
     # ./app/controllers/users/omniauth_callbacks_controller.rb:15:in `handle_auth'
     # ./app/controllers/users/omniauth_callbacks_controller.rb:6:in `facebook'
     # ./spec/controllers/users/omniauth_callbacks_controller_spec.rb:11:in `block (4 levels) in <top (required)>'
```

Reason is that (request.env["omniauth.auth"]) is nil during test. It's is a fine hash during development mode.

**Comment by dan-jensen** [comment]
@phuongnd08 this was incredibly helpful! Thanks so much for posting it for the community.

**Comment by phuongnd08** [comment]
Also, to test omniauth, you need to use request testing to trigger the whole rails middlewares. Controller testing skip some middlewares and may not invoke OmniAuth mocking.
